<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OfficeBridge.Core\OfficeBridge.Core.csproj" />
    <ProjectReference Include="..\OfficeBridge.Infrastructure\OfficeBridge.Infrastructure.csproj" />
    <ProjectReference Include="..\OfficeBridge.TemplateEngine\OfficeBridge.TemplateEngine.csproj" />
    <Resource Include="Assets\logo.png" />
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\OfficeBridge.ico</ApplicationIcon>
  </PropertyGroup>


  <ItemGroup>
    <Resource Include="Assets\OfficeBridge.ico" />
    <Content Include="..\Templates\**\*">
      <Link>Templates\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

